[package]
name = "bufferview"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]
edition = "2018"

[dependencies]
minifb = "0.11.2"

[dependencies.buffer_dump]
path = "../buffer_dump"

[dependencies.gpu-interp]
path = "../gpu-interp"
