language: rust
env: 
    - RUST_BACKTRACE=1 RUST_TEST_THREADS=1
rust:
    - stable
    - beta
    - nightly
cache: cargo
script:
    - cargo test --all
    - cargo test --all --release
    - cd testsuite && cargo run 
    - cd testsuite && cargo run --release
