[workspace]
members = [
    "./implicit",
    "./aabb-quadtree",
    "./line-stitch",
    "./vectorphile",
    "./testsuite",
    "./gpu-interp",
    "./vis_3d",
    "./buffer_dump",
    "./buffer_view"
]
