[workspace]
members = [
    "./implicit",
    "./util/aabb-quadtree",
    "./util/line-stitch",
    "./util/vectorphile",
    "./testsuite",
    "./util/gpu-interp",
    "./util/buffer_dump",
    "./util/buffer_view"
]
