[package]
name = "implicit-gpu"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[[bin]]
name = "implicit-gpu-bin"
path = "./src/main.rs"

[dependencies]
ocl = "0.11.0"
gc = "0.2.1"
lazy_static = "0.2.2"
image = "0.10.4"
