[package]
name = "implicit-gpu"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[[bin]]
name = "implicit-gpu-bin"
path = "./src/main.rs"

[dependencies]
ocl = "0.11.*"
gc = "0.2.*"
flame = "*"
lazy_static = "0.2.*"
image = "0.10.*"
itertools = "0.5.*"
lux = "0.1.2"
vecmath = "*"
fnv = "*"

#[dependencies.lux]
#path = "../lux"
