array_layout = "Block"
chain_one_line_max = 100
closure_block_indent_threshold = -1
comment_width = 60
error_on_line_overflow = false
fn_args_density = "Compressed"
fn_args_paren_newline = false
fn_call_style = "Block"
fn_call_width = 80
fn_single_line = true
generics_indent = "Block"
max_width = 150
reorder_imports = true
reorder_imported_names = true
struct_lit_width = 30
use_try_shorthand = true
where_density = "Compressed"
where_layout = "Horizontal"
wrap_comments = true
write_mode = "Overwrite"
