[package]
name = "vectorphile"
version = "0.1.4-pre"
authors = ["Ty Overby <ty@pre-alpha.com>"]
license = "MIT/Apache-2.0"
description = "A library for vector drawing with multiple output types"

[dependencies]
euclid = "0.16.0"
