[package]
name = "extern_api"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]
edition = "2018"

[dependencies]
serde = "1.*.*"
serde_derive = "1.*.*"

[dependencies.euclid]
version = "0.19.0"
features = ["serde"]
