[package]
name = "testsuite"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies]
serde = "1.*.*"
expectation = "0.1.*"

[dependencies.snoot]
path = "../../snoot"

[dependencies.implicit]
path = "../implicit"
