[package]
name = "test-app"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]

[dependencies]
noise = ""
gfx = ""
gfx_window_glutin = ""
glutin = ""
cgmath = ""
typed-arena = ""

[dependencies.gpu-interp]
path = "../../util/gpu-interp"

[dependencies.implicit]
path = "../../implicit"
